service: scratch

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-2
  environment:
    tableName: notes

  # 'iamRoleStatements' defines the permission policy for the Lambda function.

  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  create:
    # Defines an HTTP API endpoint that calls the main function in create.js
    # - path: url path is /scratch
    # - method: POST request
    handler: create.main
    events:
      - http:
          path: scratch
          method: post
  get:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /scratch/{id}
    # - method: GET request
    handler: get.main
    events:
      - http:
          path: scratch/{id}
          method: get
  list:
    # Defines an HTTP API endpoint that calls the main function in list.js
    # - path: url path is /scratch
    # - method: GET request
    handler: list.main
    events:
      - http:
          path: scratch
          method: get
  update:
    # Defines an HTTP API endpoint that calls the main function in update.js
    # - path: url path is /scratch/{id}
    # - method: PUT request
    handler: update.main
    events:
      - http:
          path: scratch/{id}
          method: put
  delete:
    # Defines an HTTP API endpoint that calls the main function in delete.js
    # - path: url path is /scratch/{id}
    # - method: DELETE request
    handler: delete.main
    events:
      - http:
          path: scratch/{id}
          method: delete
